apiVersion: v1
kind: Service
metadata:
  name: demo-web-app-service
  namespace: default
  labels:
    app: demo-web-app
spec:
  selector:
    app: demo-web-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: demo-web-app-nodeport
  namespace: default
  labels:
    app: demo-web-app
spec:
  selector:
    app: demo-web-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  type: NodePort